name: Linting & tests

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Regular package install from checkout
        run: pip install .
      - name: Dev package install from checkout
        run: pip install .[dev]
      - name: Run tests with pytest
        run: pytest 
